### ISSUE TITLE
New Power BI icons available

### ISSUE THREAD

**Issue by mh-gd** [marclelijveld/Power-BI-Icons#1]
In the release notes of February 2021, there are some new icons presented, e.g. for Power BI Report Server.
[Link](https://powerbi.microsoft.com/de-de/blog/power-bi-february-2021-feature-summary/)
--> Chapter "New icon update"

Would be great if you could include them!

Thanks,
Martin

**Comment by marclelijveld** [comment]
Hey Martin, 

Thanks for the heads-up! I will try to add them soon. The quality of the images as they are in the blogpost is not decent enough to include (if you ask me). Work in progress :) 

Thnx, 
Marc

**Comment by mh-gd** [comment]
Yes, I could not find it anywhere else except of in the release announcement, which is why I thought you might already have a better source...

Looking at [the Fluent UI page](https://developer.microsoft.com/en-us/fluentui#/styles/web/office-brand-icons#branded-icon-library) shows that they do not even have the Power BI icon there...

I guess we then just have to wait. Thanks for taking care!

**Comment by mh-gd** [comment]
Hey @marclelijveld, I had [posted on that at the PBI community](https://community.powerbi.com/t5/Issues/Provide-the-new-PowerBI-Power-platform-icons/idc-p/1816966#M66225), but did not get a useful answer so far.

I replied there again and tagged the author of the Feature summary post. Let's see if he comments.

**Comment by jeroenterheerdt** [comment]
I am working on it - stay tuned.

**Comment by jeroenterheerdt** [comment]
🎉

**Comment by mh-gd** [comment]
Create, thanks for supporting us in that case!
